force-app/main/default/objects/FriendlyCaptchaConfig__mdt/FriendlyCaptchaConfig__mdt.object-meta.xml
<CustomObject>
	<label>FriendlyCaptchaConfig</label>
	<pluralLabel>FriendlyCaptchaConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/FriendlyCaptchaConfig__mdt/fields/APIEndpoint__c.field-meta.xml
<CustomField>
    <fullName>APIEndpoint__c</fullName>
    <defaultValue>&quot;global&quot;</defaultValue>
    <description>The endpoint URL used for communicating with the Friendly Captcha API. Shorthands &apos;eu&apos; or &apos;global&apos; are accepted. Default is &apos;global&apos;. Using the &apos;eu&apos; endpoint requires access that must be enabled in the Friendly Captcha dashboard.</description>
    <label>APIEndpoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FriendlyCaptchaConfig__mdt/fields/Sitekey__c.field-meta.xml
<CustomField>
    <fullName>Sitekey__c</fullName>
    <description>A Friendly Captcha sitekey associated with an application. Copied from the application configuration in the Friendly Captcha dashboard.</description>
    <label>Sitekey</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FriendlyCaptchaConfig__mdt/fields/StartMode__c.field-meta.xml
<CustomField>
	<fullName>StartMode__c</fullName>
	<description>The start mode determines the behavior around automatic activation of the widget. Activation here means the challenge gets requested and gets solved. 'auto' means the widget gets activated as soon as it is created. 'focus' means the widget gets activated as soon as the form above it is focused. 'none' means the widget does not start automatically at all; the user needs to press the widget. Defaults to 'focus'.</description>
	<label>StartMode</label>
	<length>100</length>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/FriendlyCaptchaConfig__mdt/fields/Theme__c.field-meta.xml
<CustomField>
	<fullName>Theme__c</fullName>
	<description>The theme for the widget. 'light' is a light theme with a white background. 'dark' is a dark theme with a dark background. 'auto' means the theme is automatically chosen based on the user's system preferences. Defaults to 'light'.</description>
	<label>Theme</label>
	<length>100</length>
	<type>Text</type>
</CustomField>

force-app/main/default/classes/SettingsController.cls
public with sharing class SettingsController {
    public class WidgetSettings {
        @AuraEnabled public String apiEndpoint;
        @AuraEnabled public String sitekey;
        @AuraEnabled public String startMode;
        @AuraEnabled public String language;
        @AuraEnabled public String theme;

        public WidgetSettings(FriendlyCaptchaConfig__mdt config) {
            this.apiEndpoint = config.APIEndpoint__c;
            this.sitekey = config.Sitekey__c;
            this.startMode = config.StartMode__c;
            this.language = config.Language__c;
            this.theme = config.Theme__c;
        }
    }

    @AuraEnabled(cacheable=true)
    public static WidgetSettings get(){
        return new WidgetSettings(FriendlyCaptchaConfig__mdt.getInstance('Settings'));
    }
}